plugins: ['jekyll/scholar']

scholar:
  style: apa
  locale: en

  sort_by: year, month 
  order: descending

  source: ./_bibliography
  bibliography: mybib.bib
  bibliography_template: bib

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
  repository: papers

  key: value


url: "" # https://licioromao.github.io/licioromao.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # _site/  # ./licioromao.gihub.io # the subpath of your site, e.g. /blog
title: "Licio Romao" # the name of your site, e.g. ACME Corp.
destination: ./docs
description: <p>Postdoctoral Researcher at Oxcav<br>Computer Science Department. Oxford University</p>

theme: academic-jekyll-theme
