menu:
- {name: 'Biography', url: '/Biography'}
- {name: 'Research', url: '/Research'}
- {name: 'Publications', url: '/Publications'}
- {name: 'Teaching', url: '/Teaching'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

research:
- {name: 'Ongoing research projects', url: 'Ongoing'}
- {name: 'Past and current students', url: 'students'}

social:
- {academia: 'yes', icon: 'google-scholar', link: 'https://scholar.google.com/citations?user=AWJbL5kAAAAJ&hl=en'}
- {academia: 'no', icon: 'linkedin', link: 'https://www.linkedin.com/in/licio-romao-58a9648b'}
- {academia: 'yes', icon: 'orcid', link: 'https://orcid.org/my-orcid?orcid=0000-0002-5716-6162'}
- {academia: 'yes', icon: 'dblp', link: 'https://dblp.org/pid/223/2586.html'}
- {academia: 'yes', icon: 'semantic-scholar', link: 'https://www.semanticscholar.org/author/Licio-Romao/51054065?sort=influence'}
- {academia: 'yes', icon: 'arxiv', link: 'https://arxiv.org/a/romao_l_1.html'}
- {academia: 'no', icon: 'github', link: 'https://github.com/licioromao'}

contacts:
- {name: 'Dr. Licio Romao', title: 'Postdoctoral Researcher', phone: "01865 273838", department: 'Computer Science', institution: 'University of Oxford', institution_address: '7 Parks Rd, Oxford OX1 3QG', email: 'MyFirstName.MyLastName[at]cs.ox.ac.uk', office: '4th floor, room 420', image: 'assets/img/contact.jpg'}
