menu:
- {name: 'Publications', url: '/Publications'}
- {name: 'Biography', url: '/Biography'}
- {name: 'Courses', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/licioromao'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/licio-romao-58a9648b'}

contacts:
- {name: 'Dr. Licio Romao', title: 'Postdoctoral Researcher', phone: "01865 273838", department: 'Computer Science', institution: 'University of Oxford', institution_address: '7 Parks Rd, Oxford OX1 3QG', email: 'MyFirstName.MyLastName[at]cs.ox.ac.uk', office: '4th floor, room 420', image: 'assets/img/contact.jpg'}
